export enum EmployeeEnum {
	nationalId= "National ID",
	firstName= "First Name",
	lastName= "Last Name",
	DOB= "Date of Birth",
	gender= "Gender",
	maritalStatus= "Marital Status",
	country= "Country",
	city= "City",
	address= "Address",
	phone= "Phone",
	hireDate= "Hire Date",
	monthlySalary= "Monthly Salary",
	department= "Department",
	qualifications= "Qualifications",
	workPermitId= "Work Permit Id",
	workPermitExpiryDate= "Work Permit Expiry Date",
	employeePhoto= "Employee Photo",
 }